In [1]:
from pathlib import Path

import numpy as np
import pandas as pd

In [2]:
data_path = Path("forest_fires_dataset.csv")
data_path.exists()

True

In [3]:
with data_path.open("r", encoding="utf-8") as file:
    for line_number in range(15):
        line = file.readline()
        print(line_number + 1, repr(line))

1 'Cordillera,,,,,,,,,,,,,\n'
2 'day,month,year,Temperature, RH, Ws,Rain ,FFMC,DMC,DC,ISI,BUI,FWI,Classes  \n'
3 '1,6,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire   \n'
4 '2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire   \n'
5 '3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire   \n'
6 '4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire   \n'
7 '5,6,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire   \n'
8 '6,6,2012,31,67,14,0,82.6,5.8,22.2,3.1,7,2.5,fire   \n'
9 '7,6,2012,33,54,13,0,88.2,9.9,30.5,6.4,10.9,7.2,fire   \n'
10 '8,6,2012,30,73,15,0,86.6,12.1,38.3,5.6,13.5,7.1,fire   \n'
11 '9,6,2012,25,88,13,0.2,52.9,7.9,38.8,0.4,10.5,0.3,not fire   \n'
12 '10,6,2012,28,79,12,0,73.2,9.5,46.3,1.3,12.6,0.9,not fire   \n'
13 '11,6,2012,31,65,14,0,84.5,12.5,54.3,4,15.8,5.6,fire   \n'
14 '12,6,2012,26,81,19,0,84,13.8,61.4,4.8,17.7,7.1,fire   \n'
15 '13,6,2012,27,84,21,1.2,50,6.7,17,0.5,6.7,0.2,not fire   \n'

In [4]:
df_raw = pd.read_csv(
    data_path,
    header=None,
    dtype=str
)

df_raw.head(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,Cordillera,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
2,1,6,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
3,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
4,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire
5,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire
6,5,6,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire
7,6,6,2012,31,67,14,0,82.6,5.8,22.2,3.1,7,2.5,fire
8,7,6,2012,33,54,13,0,88.2,9.9,30.5,6.4,10.9,7.2,fire
9,8,6,2012,30,73,15,0,86.6,12.1,38.3,5.6,13.5,7.1,fire

In [5]:
df_raw.shape

(249, 14)

In [6]:
region_names = ["Cordillera", "Hudson Bay"]

is_region_row = (
    df_raw[0].str.strip().isin(region_names)
)

df_raw.loc[is_region_row]

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,Cordillera,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
125,Hudson Bay,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
# Add a new column for the region and fill it down the rows
df_raw["Region"] = df_raw[0].where(is_region_row)
df_raw["Region"] = df_raw["Region"].ffill()

df_raw.head(10)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,Region
0,Cordillera,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cordillera
1,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Cordillera
2,1,6,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire,Cordillera
3,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire,Cordillera
4,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire,Cordillera
5,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire,Cordillera
6,5,6,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire,Cordillera
7,6,6,2012,31,67,14,0,82.6,5.8,22.2,3.1,7,2.5,fire,Cordillera
8,7,6,2012,33,54,13,0,88.2,9.9,30.5,6.4,10.9,7.2,fire,Cordillera
9,8,6,2012,30,73,15,0,86.6,12.1,38.3,5.6,13.5,7.1,fire,Cordillera

In [8]:
day_numeric = pd.to_numeric(
    df_raw[0].str.strip(),
    errors="coerce"
)

# a clean observation has a numeric day value, so we can use that to filter out the non-observation rows
is_observation = day_numeric.notna()
df_clean = df_raw.loc[is_observation].copy()
df_clean.shape

(244, 15)

In [9]:
# The actual column names are stored in row 1 of df_raw

column_names = (
    df_raw.loc[1, list(range(14))]
    .str.strip()
    .tolist()
)

df_clean.columns = column_names + ["Region"]

df_clean.head()

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Region
2,1,6,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire,Cordillera
3,2,6,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire,Cordillera
4,3,6,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire,Cordillera
5,4,6,2012,25,89,13,2.5,28.6,1.3,6.9,0,1.7,0,not fire,Cordillera
6,5,6,2012,27,77,16,0,64.8,3,14.2,1.2,3.9,0.5,not fire,Cordillera

In [10]:
df_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 15 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       248 non-null    str
 1   1       246 non-null    str
 2   2       246 non-null    str
 3   3       246 non-null    str
 4   4       246 non-null    str
 5   5       246 non-null    str
 6   6       246 non-null    str
 7   7       246 non-null    str
 8   8       246 non-null    str
 9   9       246 non-null    str
 10  10      246 non-null    str
 11  11      246 non-null    str
 12  12      246 non-null    str
 13  13      245 non-null    str
 14  Region  249 non-null    str
dtypes: str(15)
memory usage: 29.3 KB

In [11]:
df_clean.reset_index(drop=True, inplace=True)
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          244 non-null    str
 1   month        244 non-null    str
 2   year         244 non-null    str
 3   Temperature  244 non-null    str
 4   RH           244 non-null    str
 5   Ws           244 non-null    str
 6   Rain         244 non-null    str
 7   FFMC         244 non-null    str
 8   DMC          244 non-null    str
 9   DC           244 non-null    str
 10  ISI          244 non-null    str
 11  BUI          244 non-null    str
 12  FWI          244 non-null    str
 13  Classes      243 non-null    str
 14  Region       244 non-null    str
dtypes: str(15)
memory usage: 28.7 KB

In [12]:
df_clean[df_clean["Classes"].isna()]

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes,Region
165,14,7,2012,37,37,18,0.2,88.9,12.9,14.6 9,12.5,10.4,fire,NaN,Hudson Bay

In [13]:
df_clean.loc[165]

day                    14
month                   7
year                 2012
Temperature            37
RH                     37
Ws                     18
Rain                  0.2
FFMC                 88.9
DMC                  12.9
DC                 14.6 9
ISI                  12.5
BUI                  10.4
FWI               fire
Classes               NaN
Region         Hudson Bay
Name: 165, dtype: str

In [14]:
# row is shifted due to a missing comma

df_clean.loc[
    165,
    ["DC", "ISI", "BUI", "FWI", "Classes"]
] = ["14.6", "9", "12.5", "10.4", "fire"]

df_clean.loc[165]

day                    14
month                   7
year                 2012
Temperature            37
RH                     37
Ws                     18
Rain                  0.2
FFMC                 88.9
DMC                  12.9
DC                   14.6
ISI                     9
BUI                  12.5
FWI                  10.4
Classes              fire
Region         Hudson Bay
Name: 165, dtype: str

In [15]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          244 non-null    str
 1   month        244 non-null    str
 2   year         244 non-null    str
 3   Temperature  244 non-null    str
 4   RH           244 non-null    str
 5   Ws           244 non-null    str
 6   Rain         244 non-null    str
 7   FFMC         244 non-null    str
 8   DMC          244 non-null    str
 9   DC           244 non-null    str
 10  ISI          244 non-null    str
 11  BUI          244 non-null    str
 12  FWI          244 non-null    str
 13  Classes      244 non-null    str
 14  Region       244 non-null    str
dtypes: str(15)
memory usage: 28.7 KB

In [16]:
numeric_columns = [
    "day",
    "month",
    "year",
    "Temperature",
    "RH",
    "Ws",
    "Rain",
    "FFMC",
    "DMC",
    "DC",
    "ISI",
    "BUI",
    "FWI"
]

df_clean[numeric_columns] = df_clean[numeric_columns].apply(
    pd.to_numeric,
    errors="raise"
)

df_clean.dtypes

day              int64
month            int64
year             int64
Temperature      int64
RH               int64
Ws               int64
Rain           float64
FFMC           float64
DMC            float64
DC             float64
ISI            float64
BUI            float64
FWI            float64
Classes            str
Region             str
dtype: object

In [17]:
df_clean["Date"] = pd.to_datetime(
    df_clean[["year", "month", "day"]]
)

df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          244 non-null    int64
 1   month        244 non-null    int64
 2   year         244 non-null    int64
 3   Temperature  244 non-null    int64
 4   RH           244 non-null    int64
 5   Ws           244 non-null    int64
 6   Rain         244 non-null    float64
 7   FFMC         244 non-null    float64
 8   DMC          244 non-null    float64
 9   DC           244 non-null    float64
 10  ISI          244 non-null    float64
 11  BUI          244 non-null    float64
 12  FWI          244 non-null    float64
 13  Classes      244 non-null    str
 14  Region       244 non-null    str
 15  Date         244 non-null    datetime64[us]
dtypes: datetime64[us](1), float64(7), int64(6), str(2)
memory usage: 30.6 KB

In [18]:
# Check categorical values
print(df_clean["Classes"].value_counts(dropna=False))
print(df_clean["Region"].value_counts(dropna=False))

Classes
fire             131
not fire         101
fire               5
fire               2
not fire           2
not fire           1
not fire           1
not fire           1
Name: count, dtype: int64
Region
Cordillera    122
Hudson Bay    122
Name: count, dtype: int64

In [19]:
# strip str columns
df_clean["Classes"] = df_clean["Classes"].str.strip()
df_clean["Region"] = df_clean["Region"].str.strip()

# strip column names
df_clean.columns = df_clean.columns.str.strip()

# verify the categories
print(df_clean["Classes"].unique())
print(df_clean["Region"].unique())

<StringArray>
['not fire', 'fire']
Length: 2, dtype: str
<StringArray>
['Cordillera', 'Hudson Bay']
Length: 2, dtype: str

In [20]:
# check for duplicates
df_clean.duplicated().sum()

np.int64(0)

In [21]:
df_clean.to_csv("forest_fires_clean.csv", index=False)